[project]
name = "test-tetrika"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiohttp>=3.12.13",
    "bs4>=0.0.2",
    "loguru>=0.7.3",
]
